// ========== DOSYA: sentinel-tearsheet/src/main.rs ==========
use anyhow::{Context, Result};
use clap::Parser;
use serde::Deserialize;
use std::fs::File;
use std::io::Write;
use tracing::info;

#[derive(Parser, Debug)]
#[command(author, version, about = "VQ-Capital Tearsheet Generator", long_about = None)]
struct Args {
    #[arg(short, long, default_value = "http://localhost:19000")]
    questdb_url: String,

    #[arg(short, long, default_value = "TEARSHEET.md")]
    output: String,
}

#[derive(Deserialize, Debug)]
struct TradeRecord {
    // Deserialize sırasında kolon eşleşmesi için buradalar ama
    // rapor özetinde kullanılmadıkları için '_' ile işaretlendiler.
    #[serde(rename = "symbol")]
    _symbol: String,
    #[serde(rename = "side")]
    _side: String,
    #[serde(rename = "pnl")]
    pnl: f64,
    #[serde(rename = "latency_ms")]
    latency_ms: f64,
    #[serde(rename = "timestamp")]
    _timestamp: String,
}

#[derive(Deserialize, Debug)]
struct PerformanceRecord {
    #[serde(rename = "drawdown_pct")]
    drawdown_pct: f64,
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt::init();
    let args = Args::parse();

    info!("📊 VQ-Alpha Raporlama Ünitesi Başlatıldı.");

    // 1. İşlem Verilerini Çek (Sadece gerekli kolonlar)
    let trades_query = "SELECT symbol, side, pnl, latency_ms, timestamp FROM paper_trades";
    let trades_url = format!(
        "{}/exp?query={}",
        args.questdb_url,
        urlencoding::encode(trades_query)
    );

    let trades_csv = reqwest::get(&trades_url)
        .await
        .context("QuestDB bağlantı hatası")?
        .text()
        .await
        .context("CSV okuma hatası")?;

    let mut trade_reader = csv::ReaderBuilder::new()
        .flexible(true)
        .from_reader(trades_csv.as_bytes());

    let mut total_trades = 0;
    let mut winning_trades = 0;
    let mut net_pnl = 0.0;
    let mut gross_profit = 0.0;
    let mut gross_loss = 0.0;
    let mut total_latency = 0.0;
    let mut trade_returns: Vec<f64> = Vec::with_capacity(1000);

    for t in trade_reader.deserialize::<TradeRecord>().flatten() {
        total_trades += 1;
        net_pnl += t.pnl;
        total_latency += t.latency_ms;

        if t.pnl > 0.0 {
            winning_trades += 1;
            gross_profit += t.pnl;
        } else {
            gross_loss += t.pnl.abs();
        }
        trade_returns.push(t.pnl);
    }

    // 2. Risk Verilerini Çek
    let perf_query = "SELECT drawdown_pct FROM performance";
    let perf_url = format!(
        "{}/exp?query={}",
        args.questdb_url,
        urlencoding::encode(perf_query)
    );
    let perf_csv = reqwest::get(&perf_url).await?.text().await?;
    let mut perf_reader = csv::ReaderBuilder::new().from_reader(perf_csv.as_bytes());
    let mut max_drawdown_pct = 0.0;

    for p in perf_reader.deserialize::<PerformanceRecord>().flatten() {
        if p.drawdown_pct > max_drawdown_pct {
            max_drawdown_pct = p.drawdown_pct;
        }
    }

    // 3. İstatistiksel Hesaplamalar
    let win_rate = if total_trades > 0 {
        (winning_trades as f64 / total_trades as f64) * 100.0
    } else {
        0.0
    };
    let profit_factor = if gross_loss > 0.0 {
        gross_profit / gross_loss
    } else {
        99.0
    };
    let avg_latency = if total_trades > 0 {
        total_latency / total_trades as f64
    } else {
        0.0
    };

    // Sharpe Ratio Hesaplaması
    let sharpe_ratio = if total_trades > 1 {
        let mean_return = net_pnl / total_trades as f64;
        let mut variance = 0.0;
        for r in &trade_returns {
            variance += (r - mean_return).powi(2);
        }
        let std_dev = (variance / total_trades as f64).sqrt();
        if std_dev > 0.0 {
            mean_return / std_dev
        } else {
            0.0
        }
    } else {
        0.0
    };

    // 4. Raporu Diske Damgala
    let report = format!(
        "
# 🦅 VQ-CAPITAL QUANTITATIVE TEARSHEET
**Date Generated:** `{}`

## 1. 📊 EXECUTIVE SUMMARY
| Metric | Value |
|---|---|
| **Total Trades Processed** | `{}` |
| **Win Rate** | `{:.2}%` |
| **Net PnL** | `${:.4}` |
| **Profit Factor** | `{:.2}` |

## 2. 📉 RISK & RETURN METRICS
| Metric | Value | Status |
|---|---|---|
| **Max Drawdown** | `{:.2}%` | {} |
| **Sharpe Ratio** | `{:.2}` | {} |

## 3. ⚡ EXECUTION & SLA METRICS
| Metric | Value | Note |
|---|---|---|
| **Average Latency** | `{:.2} ms` | Target < 25ms |

---
*Generated by VQ-Alpha Reporting Engine.*
",
        chrono::Utc::now().to_rfc2822(),
        total_trades,
        win_rate,
        net_pnl,
        profit_factor,
        max_drawdown_pct,
        if max_drawdown_pct > 15.0 {
            "🔴 DANGER"
        } else {
            "🟢 SAFE"
        },
        sharpe_ratio,
        if sharpe_ratio > 1.0 {
            "🟢 ALPHA"
        } else {
            "🔴 NOISE"
        },
        avg_latency
    );

    let mut file = File::create(&args.output)?;
    file.write_all(report.as_bytes())?;
    info!("✅ Tearsheet Başarıyla Oluşturuldu -> {}", args.output);
    Ok(())
}
